### ISSUE TITLE
Need to follow a convention for the repository folder structure

### ISSUE THREAD

**Issue by imesh** [wso2/cloudformation-is#5]
**Description:**
As it seems like the Identity Server Cloud Formation repository has not followed the convention used in the API Manager Cloud Formation repository. It would be vital to follow a standard across all WSO2 Cloud Formation repositories for maintaining Cloud Formation templates of product deployment patterns, Packer AMI creation scripts, etc.

**Affected Product Version:**
5.3.0, 5.4.0

**Comment by imesh** [comment]
**Description:**
@kasunbg @malithie As I see it might be redundant to have a folder with the name "cloudformation-templates" at the root level as the git repository name itself has already mentioned it:

````bash
/cloudformation-templates/pattern-1/
/cloudformation-templates/pattern-2/
````

I would like to propose to move the deployment pattern folders to the root level as follows:

````bash
/pattern-1/
/pattern-2/
````

**Comment by kasunbg** [comment]
Hi Imesh,

+1 to remove cloudformation-templates/ directory.

Instead of using generic names such as pattern-1, pattern-2, shall we use a short meaningful name that describes the pattern? To highlight the order of patterns, we can prepend the pattern number. The reason is that it is a bit hard to understand what the pattern is actually about unless we dig into the directory, and read the README.md.

For ex: 
* 01-two-node-is-cluster
* 02-is-cluster-with-analytics

WDYT?
